# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

##########################################################################################
# Be sure to edit the values below
##########################################################################################

title: FICAM Architecture
email: icam@gsa.gov
description: Helping the U.S. Federal Government Enterprise design, procure, integrate, and operate Federal Enterprise Identity, Credential, and Access Management services.
baseurl: ""
repourl: "https://github.com/GSA/ficam-playbooks"

#for site map search
url: https://playbooks.idmanagement.gov

# GitHub information
# This is used for adding an edit this page link to the footer
github_info:
  organization: GSA
  repository: ficam-playbooks
  default_branch: staging

# Twitter handle. Only the handle, not the URL.
# twitter: 18F

dap:
  agency: GSA

  # Optional
  # subagency: your-subagency

# Configuration for Google Analytics
ga:
  # ua: your-ua

# Site Navigation
primary_navigation:
  - name: Home
    url: /
  - name: Architecture
    children:
      - name: Introduction
        url: /arch/
      - name: Goals and Objectives
        url: /arch/goals/
      - name: Services Framework
        url: /arch/services/
      - name: Use Case
        url: /arch/usecases/
      - name: System Components
        url: /arch/components/
      - name: Standards and Policies
        url: /arch/standards/
  - name: Identity
    children:
      - name: Identity Management Overview
        url: /arch/services/#identity-management
      - name: Cloud Identity
        url: /playbooks/cloud/
      - name: Privileged Identity (Coming Soon)
      - name: Digital Worker Identity
        url: /playbooks/dw/
      - name: Identity Lifecycle Management
        url: /playbooks/ilm/
  - name: Credential
    children:
      - name: Credential Management Overview
        url: /arch/services/#credential-management
      - name: Federal PKI
        url: /fpki/
      - name: PIV Card
        url: /piv/
      - name: PIV Interoperable Card
        url: /playbooks/pivi/
      - name: Phishing-Resistant Authenticators (Coming Soon)
  - name: Access
    children:
      - name: Access Management Overview
        url: /arch/services/#access-management
      - name: Physical Access
        url: /pacs/
      - name: Single Sign-On
        url: /playbooks/sso/
  - name: Federation
    children:
      - name: Federation Overview
        url: /arch/services/#federation
      - name: Application Federation
        url: /playbooks/sso/#step-5-federate-application-access
      - name: Attribute supported Federation
        url: /playbooks/ilm/#step-4-integrate-with-agency-enterprise-services
  - name: Governance
    children:
      - name: Governance Overview
        url: /arch/services/#governance
      - name: ICAM Program Management
        url: /pm/
      - name: Digital Identity Risk Assessment
        url: /playbooks/dira/
      - name: ICAM Governance Framework
        url: /docs/playbook-identity-governance-framework.pdf
  - name: User Guides
    children:
      - name: Digitally Sign Word Document
        url: /playbooks/signword/
      - name: Digitally Sign Email in Outlook
        url: /piv/user-guide/outlook/
      - name: Digitally Sign Federal Register Document
        url: /playbooks/signfedregister/
      - name: PIV-Enable Windows Domain
        url: /piv/network/
      - name: PIV-Enable macOS
        url: /piv/network/mac/
      - name: Troubleshoot PIV Windows Logon
        url: /piv/network/troubleshooting/
      - name: PIV-Enable Firefox
        url: /piv/engineer/firefox/
      - name: PIV-Enable SSH
        url: /piv/engineer/ssh/
  - name: Tools
    children: 
      - name: FPKI System Change Notifications
        url: /fpki/notifications/
      - name: FPKI Useful Tools
        url: /fpki/tools/

secondary_navigation:
  - name: Contact Us
    url: https://www.idmanagement.gov/contact-us/
  - name: About Us
    url: https://www.idmanagement.gov/about-us/
  - name: Contribute
    url: https://www.idmanagement.gov/contribute/

# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
searchgov:

  # You should not change this.
  endpoint: https://search.usa.gov

  # replace this with your search.gov account
  affiliate: idmprod

  # replace with your access key
  access_key: zCEoL5u4U5XFzfFSxy8y4Iz6vdtTjsb4U539L_rgDTM=

  # this renders the results within the page instead of sending to user to search.gov
  inline: false

##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################

collections:
  ficampm:
    output: true
    permalink: /pm/:path/
  arch:
    output: true
    permalink: /arch/:path/
  fpki:
    output: true
    permalink: /fpki/:path/
  pacs:
    output: true
    permalink: /pacs/:path/
  piv:
    output: true
    permalink: /piv/:path/
  playbooks:
    output: true
    permalink: /playbooks/:path/
  pages:
    output: true
    permalink: /:path/

permalink: pretty

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: "posts"
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 3
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: "/page/:num/" # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ":title - page :num"
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: "date"
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: "posts"
  # Optional, the default tag to use, omit to disable
  tag: ""
  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ""
  # Optional,omit or set both before and after to zero to disable.
  # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2
  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html
  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: "index.html"

exclude:
  - package.json
  - package-lock.json
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md
  - degit.json
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml

assets:
  autoprefixer:
    browsers:
      - "> 2%"
      - "last 2 versions"
      - "IE 11"
      - "not dead"
  sources:
    - node_modules/uswds/dist/img
    - node_modules/uswds/dist/js
    - node_modules/uswds/dist/scss
    - node_modules/netlify-cms/dist
