# List of playbooks to include on the Playbooks page in additon to the
# FICAM-produced playbooks located in the /_playbooks/ and PDF versions in /assets/playbooks folder.
# Newest on top

- title: Enterprise Single Sign-On Playbook
  type: PDF
  pubdate: 2021-02
  description: The Enterprise SSO Playbook is a five-step playbook to aid agencies in planning an SSO or Identity Federation service.
  url: /docs/playbook-sso.pdf

- title: Digital Worker Identity Playbook
  type: PDF
  pubdate: 2021-01
  description: The Digital Worker Identity Playbook is a practical guide to manage digital worker identities.
  url: /docs/playbook-digital-worker.pdf

- title: Digital Identity Risk Assessment Playbook
  type: PDF
  pubdate: 2020-09
  description: The Digital Identity Risk Assessment playbook is a six-step playbook to complete a digital identity risk assessment as described in OMB Memo 19-17 and NIST Special Publication 800-63-3.
  url: /docs/playbook-dira.pdf

- title: Federal Identity, Credential, and Access Management Roadmap Version 2.0
  type: PDF
  pubdate: 2011-12
  description: The FICAM Roadmap contains processes, procedures, and considerations for planning and managing identity, credential, and access management programs. Note, the enterprise architecture section has been superseded by the FICAM Architecture.
  url: https://www.idmanagement.gov/docs/roadmap-ficam.pdf
